[bun]
format = "via [$symbol]($style)"
symbol = "bun "

[buf]
format = "via [$symbol]($style)"

[cmake]
format = "via [$symbol]($style)"
symbol = "cmake "

[cobol]
format = "via [$symbol]($style)"
symbol = "cobol "

[crystal]
format = "via [$symbol]($style)"
symbol = "cr "

[daml]
format = "via [$symbol]($style)"
symbol = "daml "

[dart]
format = "via [$symbol]($style)"
symbol = "dart "

[deno]
format = "via [$symbol]($style)"
symbol = "deno "

[dotnet]
format = "[$symbol(🎯 $tfm )]($style)"
symbol = ".NET "

[elixir]
format = "via [$symbol]($style)"
symbol = "exs "

[elm]
format = "via [$symbol]($style)"
symbol = "elm "

[erlang]
format = "via [$symbol]($style)"

[fennel]
format = "via [$symbol]($style)"
symbol = "fnl "

[golang]
format = "via [$symbol]($style)"
symbol = "go "

[gradle]
format = "via [$symbol]($style)"
symbol = "gradle "

[haxe]
format = "via [$symbol]($style)"

[helm]
format = "via [$symbol]($style)"

[java]
format = "via [$symbol]($style)"
symbol = "java "

[julia]
format = "via [$symbol]($style)"
symbol = "jl "

[kotlin]
format = "via [$symbol]($style)"
symbol = "kt "

[lua]
format = "via [$symbol]($style)"
symbol = "lua "

[meson]
format = "via [$symbol]($style)"
symbol = "meson "

[nim]
format = "via [$symbol]($style)"
symbol = "nim "

[nodejs]
format = "via [$symbol]($style)"
symbol = "Node.js "

[ocaml]
format = "via [$symbol(\\($switch_indicator$switch_name\\) )]($style)"
symbol = "ml "

[opa]
format = "via [$symbol]($style)"
symbol = "opa "

[perl]
format = "via [$symbol]($style)"
symbol = "pl "

[php]
format = "via [$symbol]($style)"
symbol = "php "

[pulumi]
format = "via [$symbol$stack]($style)"
symbol = "pulumi "

[purescript]
format = "via [$symbol]($style)"
symbol = "purs "

[python]
format = "via [$symbol]($style)"
symbol = "Python "

[raku]
format = "via [$symbol]($style)"
symbol = "raku "

[red]
format = "via [$symbol]($style)"

[rlang]
format = "via [$symbol]($style)"

[ruby]
format = "via [$symbol]($style)"
symbol = "rb "

[rust]
format = "via [$symbol]($style)"
symbol = "Rust "

[solidity]
format = "via [$symbol]($style)"
symbol = "solidity "

[swift]
format = "via [$symbol]($style)"
symbol = "swift "

[vagrant]
format = "via [$symbol]($style)"

[vlang]
format = "via [$symbol]($style)"

[zig]
format = "via [$symbol]($style)"
symbol = "zig "

[character]
success_symbol = "[>](bold green)"
error_symbol = "[x](bold red)"
vimcmd_symbol = "[<](bold green)"

[git_commit]
tag_symbol = " tag "

[git_status]
ahead = ">"
behind = "<"
diverged = "<>"
renamed = "r"
deleted = "x"

[aws]
symbol = "aws "

[azure]
symbol = "az "

[c]
symbol = "C "

[conda]
symbol = "conda "

[directory]
read_only = " ro"

[docker_context]
symbol = "docker "

[fossil_branch]
symbol = "fossil "

[gcloud]
symbol = "gcp "

[git_branch]
symbol = ""

[guix_shell]
symbol = "guix "

[hg_branch]
symbol = "hg "

[memory_usage]
symbol = "memory "

[nix_shell]
symbol = "nix "

[os.symbols]
Alpaquita = "alq "
Alpine = "alp "
Amazon = "amz "
Android = "andr "
Arch = "rch "
Artix = "atx "
CentOS = "cent "
Debian = "deb "
DragonFly = "dfbsd "
Emscripten = "emsc "
EndeavourOS = "ndev "
Fedora = "fed "
FreeBSD = "fbsd "
Garuda = "garu "
Gentoo = "gent "
HardenedBSD = "hbsd "
Illumos = "lum "
Linux = "lnx "
Mabox = "mbox "
Macos = "mac "
Manjaro = "mjo "
Mariner = "mrn "
MidnightBSD = "mid "
Mint = "mint "
NetBSD = "nbsd "
NixOS = "nix "
OpenBSD = "obsd "
OpenCloudOS = "ocos "
openEuler = "oeul "
openSUSE = "osuse "
OracleLinux = "orac "
Pop = "pop "
Raspbian = "rasp "
Redhat = "rhl "
RedHatEnterprise = "rhel "
Redox = "redox "
Solus = "sol "
SUSE = "suse "
Ubuntu = "ubnt "
Unknown = "unk "
Windows = "win "

[package]
symbol = ""

[pijul_channel]
symbol = "pijul "

[scala]
symbol = "scala "

[spack]
symbol = "spack "

[status]
symbol = "[x](bold red) "

[sudo]
symbol = "sudo "

[terraform]
symbol = "terraform "
